# Generated by Django 4.2 on 2023-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='номер заказа')),
                ('prise_usd', models.IntegerField(verbose_name='цена в долларах')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
                ('prise_rub', models.IntegerField(verbose_name='цена в рублях')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
